export const productById1: IProductSeller = {
  id: 1,
  name: "Áo T-shirt nam",
  priceMin: 72331,
  priceMax: 105000,
  priceMinBeforeDiscount: 103330,
  priceMaxBeforeDiscount: 150000,
  showDiscount: 30,
  description: "không",
  status: 1,
  image:
    "https://firebasestorage.googleapis.com/v0/b/store-ccbcb.appspot.com/o/ecommerceSavani%2Ftshirt_nam_khong_tui.jpg?alt=media&token=5f98d72b-709c-48bc-9b60-669534c92109",
  images: null,
  promotionId: 3,
  sold: 12,
  stock: 456,
  tierVariations: [
    {
      name: "Màu sắc",
      options: ["đỏ", "xanh", "đen"],
    },
    {
      name: "Size",
      options: ["S", "M", "L"],
    },
  ],
  models: [
    {
      id: 1,
      sku: "TSM-001-R-S",
      name: "đỏ,S",
      image: null,
      price: 84000,
      priceBeforeDiscount: 120000,
      showDiscount: 30,
      sold: 2,
      stock: 12,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 2,
      sku: "TSM-002-R-M",
      name: "M,đỏ",
      image: null,
      price: 86100,
      priceBeforeDiscount: 123000,
      showDiscount: 30,
      sold: 3,
      stock: 0,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 3,
      sku: "TSM-003-R-L",
      name: "L,đỏ",
      image: null,
      price: 86100,
      priceBeforeDiscount: 123000,
      showDiscount: 30,
      sold: 34,
      stock: 12,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 4,
      sku: "TSM-004-BL-S",
      name: "đen,S",
      image: null,
      price: 105000,
      priceBeforeDiscount: 150000,
      showDiscount: 30,
      sold: 34,
      stock: 66,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 5,
      sku: "TSM-005-BL-M",
      name: "đen,M",
      image: null,
      price: 72331,
      priceBeforeDiscount: 103330,
      showDiscount: 30,
      sold: 34,
      stock: 66,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 6,
      sku: "TSM-006-BL-L",
      name: "đen,L",
      image: null,
      price: 72331,
      priceBeforeDiscount: 103330,
      showDiscount: 30,
      sold: 34,
      stock: 0,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 7,
      sku: "TSM-007-GR-S",
      name: "xanh,S",
      image: null,
      price: 72331,
      priceBeforeDiscount: 103330,
      showDiscount: 30,
      sold: 34,
      stock: 256,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 8,
      sku: "TSM-008-GR-M",
      name: "xanh,M",
      image: null,
      price: 72331,
      priceBeforeDiscount: 103330,
      showDiscount: 30,
      sold: 34,
      stock: 0,
      featured: null,
      productId: 1,
      status: null,
    },
    {
      id: 9,
      sku: "TSM-009-GR-L",
      name: "xanh,L",
      image: null,
      price: 72331,
      priceBeforeDiscount: 103330,
      showDiscount: 30,
      sold: 33,
      stock: 44,
      featured: null,
      productId: 1,
      status: null,
    },
  ],
};
